set_property SRC_FILE_INFO {cfile:/projects/01_PL_LED_TEST/PL_LED_TEST/PL_LED_TEST.srcs/constrs_1/new/LED_XDC.xdc rfile:../../../PL_LED_TEST.srcs/constrs_1/new/LED_XDC.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P20 [get_ports led]
