set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RSTn]
set_property PACKAGE_PIN P20 [get_ports LED1]
set_property PACKAGE_PIN P21 [get_ports LED2]
set_property PACKAGE_PIN M19 [get_ports CLK]
set_property PACKAGE_PIN K21 [get_ports RSTn]